const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

function buildContractAbiFile(address, abi) {
  return `// Auto-generated by hardhat/scripts/deploy.js
const CONTRACT_ADDRESS = "${address}";
const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};

if (typeof window !== "undefined") {
  window.CONTRACT_ADDRESS = CONTRACT_ADDRESS;
  window.CONTRACT_ABI = CONTRACT_ABI;
}
`;
}

async function main() {
  const SmartFarm = await hre.ethers.getContractFactory("SmartFarm");
  const smartFarm = await SmartFarm.deploy();
  await smartFarm.deployed();

  console.log("SmartFarm deployed to:", smartFarm.address);

  const artifactPath = path.join(__dirname, "..", "..", "artifacts", "contracts", "SmartFarm.sol", "SmartFarm.json");
  const frontendAbiPath = path.join(__dirname, "..", "..", "frontend", "contract_abi.js");
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  fs.writeFileSync(frontendAbiPath, buildContractAbiFile(smartFarm.address, artifact.abi));
  console.log("Updated frontend/contract_abi.js");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});